### ISSUE TITLE
NewLine tag or 0A hex

### ISSUE THREAD

**Issue by wandersonareis** [rotaryphone111/BdatEditor-Python#1]
Would it be possible to add a tag for new line or "\r"?
Even keeping the Hex 0A helps.

When I open the bdat file the line with the text does not show the new line. I have to manually adjust the UI.

It would be even better if you could extract the texts into a Json file or similar.
Editing the text directly without knowing where it has "\r" is impractical.
![1](https://user-images.githubusercontent.com/9261306/125010252-90630480-e03c-11eb-930e-8abe0477fb04.png)
![2](https://user-images.githubusercontent.com/9261306/125010258-935df500-e03c-11eb-94ba-d68ef4da9910.png)
Copying the text and pasting it into a text editor increases the work.

**Comment by rotaryphone111** [comment]
I wasn't really aware there are even instances of \r in the text, are you adding them?

**Comment by rotaryphone111** [comment]
Anyway, I'll look into it. I'm not going to pretend to be extremely experienced with UI code here. The way I have it implemented adding tags is probably going to be a bit of a pain, but it should be possible.

**Comment by wandersonareis** [comment]
NewLine use hex 0A. Change 0A to \r in BdatReader and \r to 0A in BdatWriter. 
This seems to be done because the tool recognizes the new line in the Editor and writes hex 0A to the Bdat file.  It's just not made for human reading using \r or other code.

**Comment by rotaryphone111** [comment]
"Cross platform"
![Screenshot from 2021-07-09 17-13-03](https://user-images.githubusercontent.com/6200923/125146065-f3a27480-e0d8-11eb-85af-b4966963716b.png)

**Comment by rotaryphone111** [comment]
Alright I guess I'll just add a tick box or something to toggle it on and off, is that an acceptable solution to you?

**Comment by wandersonareis** [comment]
> "Cross platform"
> ![Screenshot from 2021-07-09 17-13-03](https://user-images.githubusercontent.com/6200923/125146065-f3a27480-e0d8-11eb-85af-b4966963716b.png)

It helps.  With that I can know where the new line is.  You have plans to do file extraction and insertion.

**Comment by rotaryphone111** [comment]
Alright sorry this took a while. It's been added.
